# MySQL Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/bookbridge_db?createDatabaseIfNotExist=true&useSSL=false
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:admin}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate Configuration for MySQL
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql=false

# Production JWT Secret (Read from Env)
jwt.secret=${JWT_SECRET_KEY:YOUR_VERY_LONG_SECURE_MOCK_PRODUCTION_SECRET_KEY_FOR_JWT}
jwt.expiration=86400000
